<?php /*

Copyright (c) 2008 Metathinking Ltd.

This file is part of Affiliates For All.

Affiliates For All is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Affiliates For All is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Affiliates For All.  If not, see
<http://www.gnu.org/licenses/>.

*/ ?>

<table class="form">
  <tr>
    <td>Total Orders:</td>
    <td><?php echo $v->currency.$v->total_orders ?></td>
  </tr>
  <tr>
    <td>Total Commission:</td>
    <td><?php echo $v->currency.$v->total_commission ?></td>
  </tr>
  <tr>
    <td>Commission Paid:</td>
    <td><?php echo $v->currency ?>0.00</td>
  </tr>
  <tr>
    <td>Commission Payable:</td>
    <td><?php echo $v->currency.$v->total_commission ?></td>
  </tr>
  <tr>
    <td>Your Affiliate Link:</td>
    <td><a href="<?php echo $v->link ?>"><?php echo $v->link ?></a></td>
  </tr>
</table>
