<?php /*

Copyright (c) 2008 Metathinking Ltd.

This file is part of Affiliates For All.

Affiliates For All is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Affiliates For All is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Affiliates For All.  If not, see
<http://www.gnu.org/licenses/>.

*/ ?>

<div id="tabs" class="medium">
  <ul>
    <li><a href="#summary"><span>Summary</span></a></li>
    <li><a href="#downloadpayments"><span>Download Payments File</span></a></li>
    <li>
      <a href="#uploadpayments"><span>Upload Completed Payments</span></a>
    </li>
  </ul>
  <div id="summary">
    <table class="form">
      <tr>
        <td>Total Orders:</td>
        <td><?php echo $v->currency.$v->total_orders ?></td>
      </tr>
      <tr>
        <td>Total Commission:</td>
        <td><?php echo $v->currency.$v->total_commission ?></td>
      </tr>
      <tr>
        <td>Commission Paid:</td>
        <td><?php echo $v->currency.$v->total_payments ?></td>
      </tr>
      <tr>
        <td>Commission Payable:</td>
        <td><?php echo $v->currency.$v->total_payable ?></td>
      </tr>
    </table>
  </div>
  <div id="downloadpayments">
    <form method="post">
      <table class="form">
        <tr>
          <td>Download payments up to and including:</td>
          <td><input id="to" type="text" size="12"/></td>
        </tr>
        <tr>
          <td class="submit" colspan="2">
            <input id="download" type="submit" value="Download"/>
          </td>
        </tr>
      </table>
    </form>
  </div>
  <div id="uploadpayments">
    <form method="post" enctype="multipart/form-data">
      <table class="form">
        <tr>
          <td>Payments file:</td>
          <td><input type="file" name="file"/></td>
        </tr>
        <tr>
          <td class="submit" colspan="2">
            <input type="submit" value="Upload"/>
          </td>
        </tr>
      </table>
    </form>
  </div>
</div>

<?php echo $v->message ?>
