<?php /*

Copyright (c) 2008 Metathinking Ltd.

This file is part of Affiliates For All.

Affiliates For All is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Affiliates For All is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Affiliates For All.  If not, see
<http://www.gnu.org/licenses/>.

*/ ?>

<div id="menu">
  <?php if($this->admin) { ?>
    <a href="admin-overview.php">Site Overview</a> |
    <a href="admin-affiliates.php">Affiliates</a> |
    <a href="admin-orders.php">All Orders</a> |
    <a href="admin-payments.php">All Payments</a> |
    <a href="overview.php">Back</a> |
  <?php } else { ?>
    <a href="overview.php">Overview</a> |
    <a href="account.php">Your Account</a> |
    <a href="orders.php">Your Orders</a> |
    <a href="payments.php">Your Payments</a> |

    <?php if($_SESSION['administrator']) { ?>
      <a href="admin-overview.php">Admin</a> |
    <?php } ?>
  <?php } ?>

  <a href="logout.php">Log Out</a>
</div>
