<?php /*

Copyright (c) 2008 Metathinking Ltd.

Author(s):
Tom Kadwill <tomkadwill@msn.com>

This file is part of Affiliates For All.

Affiliates For All is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Affiliates For All is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Affiliates For All.  If not, see
<http://www.gnu.org/licenses/>.

*/ ?>

<div id="tabs" class="wide">
  <ul>
    <li><a href="#generate"><span><?php echo __('Generate Link') ?></span></a></li>
  </ul>
  <div id="generate">
    <table class="form">
		<tr>
	        <td><?php echo __('Enter your URL(s):') ?></td>
	      </tr>
	      <tr>
	        <td>
	        	<FORM NAME="inputform" ACTION="" METHOD="GET">
	        	<?php echo __('<textarea style="resize: none;" id="inputURL" rows=6 cols=60></textarea>')?>
	        	</FORM>
			<br />
	        <?php echo __('*mutliple URLs should be separated with commas')?>
	        </td>
	      </tr>
		  <tr>
			<td>
				<?php echo __('<div style="text-align:center"><input type="button" name="linkgenbutton" onclick="generateUrl()" Value="Generate link" onClick="generateUrl();"></div>')?>
			</td>
		  </tr>
 		  <tr>
			<td>
				<?php echo __('Your URL(s) with affiliate ID:')?>
				<div id="results"></div>
			</td>
		  </tr>
    </table>
  </div>
</div>
<div id="results">
  <table id="restable" class="form">
  </table>
</div>
